inherit_from:
  - .rubocop-airbnb.yml
  - .rubocop-rspec.yml

#以下にはrubocopで検証したくないフォルダを指定する
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
