version: '3.8'
services:
  yourtuber:
    # localでの使用
    build: .
    # aws ecrでの使用
    # image: 244231949897.dkr.ecr.ap-northeast-1.amazonaws.com/yourtuber_ecr
    command: bash -c "rm -f tmp/pids/server.pid && rails s -e production"
    volumes:
      - application-data:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    depends_on:
      - db
      - selenium_chrome
    environment:
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
      DB_HOST: db
      DB_NAME: yourtuber
      DB_USER: yourtuber_user
      DB_PASSWORD: password
  selenium_chrome:
    image: selenium/standalone-chrome-debug
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3406:3406"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yourtuber
      MYSQL_USER: yourtuber_user
      MYSQL_PASSWORD: password
  web:
    # localでの使用
    build: ./nginx
    # aws ecrでの使用
    # image: 244231949897.dkr.ecr.ap-northeast-1.amazonaws.com/nginx_ecr:latest
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - "8080:8080"
    depends_on:
      - yourtuber
volumes:
    application-data:
    public-data:
    tmp-data:
    log-data:
    mysql-data:
