default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV.fetch("DB_USER_NAME") { 'yourtuber_user' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'password' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>

test:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: myapp_test

production:
  <<: *default
  host: <%= ENV['RDS_HOST'] %>
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USER_NAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>