default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  database: yourtuber
  username: yourtuber_user
  password: password

test:
  <<: *default
  host: db
  database: yourtuber
  username: yourtuber_user
  password: password

production:
  <<: *default
  host: <%= ENV['RDS_HOST'] %>
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USER_NAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  port: 3306