default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # host: <%= ENV("DB_HOST") %>
  # database: <%= ENV("DB_NAME") %>
  # username: <%= ENV("DB_USER") %>
  # password: <%= ENV("DB_PASSWORD") %>
  host: <%= ENV['RDS_HOST'] %>
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USER_NAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  port: 3306

test:
  <<: *default
  host: <%= ENV("DB_HOST") %>
  database: myapp_test
  username: <%= ENV("DB_USER") %>
  password: <%= ENV("DB_PASSWORD") %>

production:
  <<: *default
  host: <%= ENV['RDS_HOST'] %>
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USER_NAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  port: 3306