default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { db } %>
  username: <%= ENV.fetch("DATABASE_USER_NAME") { postgres } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { password } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  host: <%= ENV['RDS_HOST'] %>
  database: <%= ENV['RDS_DATABASE_NAME'] %>
  username: <%= ENV['RDS_USER_NAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>